FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./DeckAlchemist.WebApp/*.csproj ./DeckAlchemist.WebApp/
COPY ./DeckAlchemist.Support/*.csproj ./DeckAlchemist.Support/
RUN cd ./DeckAlchemist.WebApp && dotnet restore && cd ..
RUN cd ./DeckAlchemist.Support && dotnet restore && cd ..

# Copy everything else and build
COPY ./DeckAlchemist.WebApp ./DeckAlchemist.WebApp
COPY ./DeckAlchemist.Support ./DeckAlchemist.Support
RUN cd ./DeckAlchemist.WebApp && dotnet publish -c Release -o out && cd ..

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/DeckAlchemist.WebApp/out .
EXPOSE 80
ENTRYPOINT ["dotnet", "DeckAlchemist.WebApp.dll"]